# SPDX-PackageName: qospeedtest
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/rfinnie/qospeedtest
# SPDX-FileCopyrightText: © 2019 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

[project]
name = "qospeedtest"
authors = [
    {name = "Ryan Finnie", email = "ryan@finnie.org"},
]
description = "Quick-and-Dirty OoklaServer Speed Test"
readme = "README.md"
requires-python = ">=3.10"
license = "MPL-2.0"
dependencies = [
    "requests",
    "PyYAML",
]
dynamic = ["version"]

[project.optional-dependencies]
gunicorn = ["gunicorn"]

[build-system]
requires = ["setuptools>=59.6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "lib"}

[tool.setuptools.packages.find]
where = ["lib"]

[project.scripts]
qospeedtest = "qospeedtest.client:main"
qospeedtest-server = "qospeedtest.server:main"

[tool.black]
line-length = 132
