#!/usr/bin/env python3

# SPDX-PackageName: qospeedtest
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/qospeedtest
# SPDX-FileCopyrightText: © 2019 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

from pathlib import Path
from runpy import run_module
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.joinpath("lib")))
run_module("qospeedtest.server", run_name="__main__")
