#!/usr/bin/env python3

# SPDX-PackageSummary: Quick-and-Dirty OoklaServer-compatible Speed Test
# SPDX-FileCopyrightText: Copyright (C) 2019-2021 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

from pathlib import Path
from runpy import run_module
import sys


sys.path.insert(0, str(Path(__file__).resolve().parent.joinpath("lib")))
run_module("qospeedtest.server", run_name="__main__")
