#!/usr/bin/env python3

# SPDX-PackageSummary: Quick-and-Dirty OoklaServer-compatible Speed Test
# SPDX-FileCopyrightText: Copyright (C) 2019-2021 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

import sys
import os

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'lib'))
import qospeedtest.client
sys.exit(qospeedtest.client.main())
